Repository Fuenfgeld/2022TeamADataEngineeringBC, pull requests merged in 2022-04, with the labels that each got.

#20 6 übung json csv dateien einlesen
  PetlTutorial.ipynb
  firma.db
  iris.csv
  iris.json
Labels: enhancement

#31 Daten fuer den Workshop #12
  Daten/CSV/Gemuese.csv
  Daten/CSV/Getreide.csv
  Daten/CSV/Obst.csv
  Daten/JSON/Gemuese.json
  Daten/JSON/Getreide.json
  Daten/JSON/Obst.json
Labels: enhancement

#33 fix der Daten '12
  Daten/JSON/Gemuese.json
  Daten/JSON/Getreide.json
  Daten/JSON/Obst.json
Labels: bug

#29 Add all transformations of final projects #7
  PySparkTutorial.ipynb
Labels: Don't merge yet
